FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        texlive-full \
        latexmk \
        make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
